name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!frontend/**'  # âŒ ignore all changes in frontend/

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCLOUD_SERVICE_KEY }}'

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

    - name: Write Firebase Admin key to file
      run: echo '${{ secrets.FIREBASE_ADMIN_KEY }}' > serviceAccountKey.json

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/tradepulse-api:latest .

    - name: Push Docker image to Artifact Registry
      run: |
        docker push ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/tradepulse-api:latest


    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ secrets.CLOUD_RUN_SERVICE }} \
          --image ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/tradepulse-api:latest \
          --region ${{ secrets.REGION }} \
          --platform managed \
          --allow-unauthenticated \
          --timeout=600s \
          --port 8000 \
          --memory 1Gi

    - name: Clean up service account key
      if: always()
      run: rm -f serviceAccountKey.json